version: '2'

services:
  mqtt:
    build: ./MQTT-1
    ports:
      - "1883:1883"
    volumes:
      - "./MQTT-1/app/mosquitto.conf:/etc/mosquitto/mosquitto.conf"
  mqtt-2:
    build: ./MQTT-2
    ports:
      - "1884:1884"
    volumes:
      - "./MQTT-2/app/mosquitto.conf:/etc/mosquitto/mosquitto.conf"
  message_router:
    build: ./message_router
    environment:
      - MQTT_SERVER_ADDRESS=35.207.111.217
      - MQTT_SERVER_PORT=1883
      - API_SERVER_ADDRESS=data_ingestion_microservice
      - API_SERVER_PORT=5000
      - ROOM_MAN_ADDRESS=35.207.111.217
      - ROOM_MAN_PORT=5003
      - API_HOST=0.0.0.0
      - API_PORT=5002
      - PYTHONUNBUFFERED=1
    ports:
      - "5002:5002"
    volumes:
      - "./message_router/app:/etc/usr/src/app"
    depends_on:
      - mqtt
      - mqtt-2
      - data_ingestion_microservice
  data_ingestion_microservice:
    build: ./data_ingestion_microservice
    ports:
      - "5000:5000" #make sure to enable this port on GCP
    links:
      - "mariaDB:mariaDB"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DB_HOST=mariaDB
      - DB_USER=dso_db_user
      - DB_PASSWORD=dso_db_password
      - DB_NAME=dso_db
    depends_on:
      - mariaDB
    volumes:
      - ./data_ingestion_microservice/app:/etc/usr/src/app
  rooms_management_microservice:
    build: ./rooms_management_microservice
    ports:
      - "5003:5000"
    links:
      - "mariaDB:mariaDB"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DB_HOST=mariaDB
      - DB_USER=dso_db_user
      - DB_PASSWORD=dso_db_password
      - DB_NAME=dso_db
      - DATA_INGESTION_API_ADDRESS=35.207.111.217
      - DATA_INGESTION_API_PORT=5000
    depends_on:
      - mariaDB
      - data_ingestion_microservice
  webapp_backend:
    build: ./webapp_backend
    ports:
      - "5001:5001" # Make sure to enable this port on GCP
    environment:
      - HOST=0.0.0.0
      - PORT=5001
      - DATA_INGESTION_API_ADDRESS=35.207.111.217
      - DATA_INGESTION_API_PORT=5000
      - MESSAGE_ROUTER_API_ADDRESS=35.207.111.217
      - MESSAGE_ROUTER_API_PORT=5002
    depends_on:
      - data_ingestion_microservice
      - message_router
  mariaDB:
    image: "mariadb:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=dso_db_root_password
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    volumes:
      - ./frontend/app:/usr/local/apache2/htdocs
    depends_on:
      - webapp_backend