version: '2'

services:
  digital_twin:
    build: ./digital_twin
    environment:
      - MQTT-1_SERVER_ADDRESS=35.207.111.217
      - MQTT-1_SERVER_PORT=1883
      - MQTT-2_SERVER_ADDRESS=35.207.111.217
      - MQTT-2_SERVER_PORT=1884
      - PYTHONUNBUFFERED=1
    volumes:
      - ./digital_twin/app:/etc/usr/src/app
